### ISSUE TITLE
I am confused about this speed.

### ISSUE THREAD

**Issue by podiumdesu** [winderica/ChuangGaoFucker#1]
Open the door, check the water meter :>

**Comment by AlaricGilbert** [comment]
It seems to be faster than **Hong Kong reporters** XD.

**Comment by AlaricGilbert** [comment]
Btw, a penguin told me to remind you：
![image](https://user-images.githubusercontent.com/36405110/53692519-7fe75300-3dcc-11e9-86f4-ebb825a0819e.png)

**Comment by podiumdesu** [comment]
But I am already a junior! 😊 :>:>:> . LOL. Good luck to you👏

**Comment by winderica** [comment]
Thank you for opening the first issue!
This speed is reasonable, because we have:
* ![image](https://user-images.githubusercontent.com/13536040/53694708-a1a50200-3ded-11e9-9a5f-ef13fadcdf92.png)
* ![image](https://user-images.githubusercontent.com/13536040/53694732-fc3e5e00-3ded-11e9-9ad1-cfdef3669c9a.png)
For laptops, assuming U=20V, we can get:
![image](https://user-images.githubusercontent.com/13536040/53694814-c77ed680-3dee-11e9-971b-2f90e943b6e4.png)
Considering time cost on transmission, we might get only 1‰ of the origin speed, so the **running** speed of code is:
![image](https://user-images.githubusercontent.com/13536040/53694862-715e6300-3def-11e9-9825-6f010b6b3750.png)

**Comment by podiumdesu** [comment]
I am appreciate your effort that you show me the concise computation. Your equations are convincing. Thanks a lot.

**Comment by winderica** [comment]
🥳This issue seems to be solved, so closing. Feel free to reopen it if you have any more question.

**Comment by winderica** [comment]
@podiumdesu 呐呐呐，现在理解了吗，呐呐呐

**Comment by featherin** [comment]
Close due to lack of response and deprecation of this repo.
